# $FreeBSD$

PORTNAME=	jsonpickle
PORTVERSION=	0.9.3
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dev@freenas.org
COMMENT=	Python library for serializing any arbitrary object graph into JSON

NO_ARCH=	yes
USE_PYTHON=	autoplist concurrent distutils
USES=		python

.include <bsd.port.mk>
