# $FreeBSD$

PORTNAME=	python-redmine
PORTVERSION=	1.5.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dev@ixsystems.com
COMMENT=	Python client for Redmine

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
