# $FreeBSD$

PORTNAME=	backports.ssl_match_hostname
PORTVERSION=	3.5.0.1
CATEGORIES=	security python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	shangteus@ixsystems.com
COMMENT=	match_hostname Python backport.

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
