# $FreeBSD$

PORTNAME=	backports.ssl_match_hostname
PORTVERSION=	3.5.0.1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	shangteus@ixsystems.com
COMMENT=	match_hostname Python backport.

USES=		python
USE_PYTHON=	autoplist distutils
#USE_GITHUB=	yes
#GH_ACCOUNT=	docker
#GH_PROJECT=	docker-py

.include <bsd.port.mk>
