#!/usr/local/bin/python3
#
# Copyright (c) 2016 iXsystems, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

import os
from datastore import get_datastore
from datastore.config import ConfigStore, ConfigNode
from freenas.serviced import checkin
from freenas.utils.permissions import perm_to_oct_string, get_unix_permissions


ds = get_datastore()
cs = ConfigStore(ds)
tftpd = ConfigNode('service.tftpd', cs).__getstate__()
args = \
    ['/usr/local/libexec/in.tftpd', '-L', '-u', tftpd['username'], '-U', perm_to_oct_string(get_unix_permissions(tftpd['umask']))] +\
    ['-a', ':' + str(tftpd['port'])] + \
    (['-c'] if tftpd['allow_new_files'] else []) + \
    [tftpd['path']]

checkin()
os.execv('/usr/local/libexec/in.tftpd', args)
