# $FreeBSD$

PORTNAME=	pushbullet
PORTVERSION=	0.10.0
DISTNAME=	pushbullet.py-${PORTVERSION}
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	dev@ixsystems.com
COMMENT=	A simple python client for pushbullet.com

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
